//Doc used for implementation: https://spring.io/guides/gs/accessing-data-mysql
package com.securevault.passwordmanager.User;

import java.util.HashMap;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.securevault.passwordmanager.S3.BucketService;

import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.security.core.AuthenticationException;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/user") // This means URL's start with /user (after Application path)
@CrossOrigin(origins = "http://localhost:3000")
public class UserController {
  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @Autowired
  private PasswordEncoder passwordEncoder; // Inject BCryptPasswordEncoder

  @Autowired
  private AuthenticationManager authenticationManager;

  @Autowired
  BucketService bucketService;

  @PostMapping(path = "/register") // Map ONLY POST Requests
  public @ResponseBody String addNewUser(@RequestParam(value = "firstName") String firstName,
      @RequestParam(value = "lastName") String lastName, @RequestParam(value = "password") String password,
      @RequestParam(value = "email") String email, @RequestParam(value = "secret") String secret) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    System.out.println("/add was reached!");

    // If there is a user that already has that email, don't create them.
    // Else, create them.
    if (userRepository.findByEmail(email) != null) {
      return "A user with the email " + email + " already exists.";
    } else {
      try {
        User n = new User();
        n.setFirstName(firstName);
        n.setLastName(lastName);
        String hashedPassword = passwordEncoder.encode(password);
        System.out.println("Hashed password: " + hashedPassword);
        n.setPassword(hashedPassword);
        n.setEmail(email);
        n.setTotpSecret(secret); // sets secret used for MFA

        userRepository.save(n);

        User savedUser = userRepository.findByEmail(email);
        // Creates S3 bucket for user 
        String bucketName = "sv-p" + savedUser.getUserId();
        bucketService.createBucket(bucketName);
        
        return "User saved";
      } catch (Exception e) {
        e.printStackTrace();
        return "Error saving user: " + e.getMessage();
      }
    }
  }

  @PostMapping(path = "/login", produces = "application/json")
  public ResponseEntity<Map<String, Object>> authenticate(@RequestParam String email, 
  @RequestParam String password) {

    Map<String, Object> responseBody = new HashMap<>();
    
    User loggedInUser = userRepository.findByEmail(email);

      try {
          var authToken = new UsernamePasswordAuthenticationToken(email, password);
          var auth = authenticationManager.authenticate(authToken);
          SecurityContextHolder.getContext().setAuthentication(auth);

          responseBody.put("status", "success");
          // You can add additional user info here if needed.
          responseBody.put("userId", loggedInUser.getUserId());
          responseBody.put("firstName", loggedInUser.getFirstName());
          
          return ResponseEntity.ok(responseBody);
      } catch (AuthenticationException e) {
        responseBody.put("status", "error");
        responseBody.put("message", "Invalid credentials");
        return new ResponseEntity<>(responseBody, HttpStatus.UNAUTHORIZED);
      }

  }

  @PostMapping(path="/forgotPassword")
  public @ResponseBody String forgotPassword(@RequestParam Long userId, @RequestParam String newPassword){

    String hashedPassword = passwordEncoder.encode(newPassword);
    userRepository.forgotPassword(userId, hashedPassword);
    return "Password Updated!";

  }

  
  @PostMapping(path="/updateEmail")
  public @ResponseBody String updateEmail(@RequestParam Long userId, @RequestParam String newEmail){

    userRepository.updateEmail(userId, newEmail);
    return "Email Updated!";

  }

  @GetMapping(path = "/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }
}
